FROM ghcr.io/astral-sh/uv@sha256:51024ef5a4ab71e33a9fb14315defbf40d1e09383a6bd66d8169bda204fb59d9

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=hardlink

WORKDIR /code

# # Install dependencies using UV
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project

COPY . .
RUN uv sync --frozen --no-dev

ENV PATH="/code/.venv/bin:$PATH"
ENV PYTHONPATH=/code

CMD [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]